### PR TITLE
Update InfluxDB Integration to Version 2 & Simplify Dependencies

### PR DESCRIPTION
**Pull request by StevenSlaa**
logo
#### Summary
This pull request updates the InfluxDB integration to use **InfluxDB v2** and simplifies the Dockerfile by removing unnecessary dependencies. Key improvements and adjustments are outlined below.

#### Changes
1. **Update to InfluxDB v2**:
   - Upgraded to the latest InfluxDB v2 release (`2.7.1`), which includes a new API and enhanced features.
   - Updated setup commands and environment configuration for compatibility with v2.
   
2. **Removal of Deprecated Components**:
   - Removed Chronograf and Kapacitor, as these are no longer required with the InfluxDB v2 setup and add unnecessary complexity.
   
3. **Simplified Dockerfile**:
   - Removed unnecessary apt packages:
     - `libnginx-mod-http-lua`, `luarocks`, `lua-resty-http`, `nginx`, and `procps` packages were removed as they are not required for basic InfluxDB functionality.
   - Reduced image size by limiting installed packages to only those necessary for InfluxDB.

4. **Updated Configuration**:
   - Adjusted the `config.json` to enhance compatibility with InfluxDB v2 (removed uneccesary port configurations for v2).
   - Updated icon and logo to main accuracy of the update to InfluxDB v2.

#### Related Issues:
- #297 
- #355 
- #353 

#### Impact
This update aligns the integration with modern InfluxDB standards, reduces Docker image size, and enhances maintainability by removing redundant components. Existing users will need to follow updated setup instructions, as InfluxDB v2 uses a different authentication mechanism and configuration.

#### Tests
1. This has yet to be tested, but for some reason my fork repository is invalid. Mabye someone can tell me what's wrong.
2. Since the authentication system is different, it may need to be changed for the add-on. Yet to be tested.

### CODE REVIEW

**Comment by sinclairpaul** [comment]
How is the migration handled?

> This has yet to be tested

As you have removed nginx, yet the config and services remain, it will fail to start.

**Comment by sinclairpaul** [comment]
Think we will close this out, thanks for contributing.

**Comment by snzyeee** [comment]
Hello @sinclairpaul!

May I ask you if it's ever to plan on this integration to be a newer influx version? 

I'm missing some features from influxdb 2. Is it worth waiting or should I just switch to the other add-on? 

Thank you in advance.

**Comment by StevenSlaa** [comment]
Hi @sinclairpaul,

Thank you for your feedback on the pull request. You raise an important point regarding migration and the potential issues caused by removing nginx and the related config and services.

I completely agree that ensuring a smooth transition for users is crucial. While maintaining the older version of InfluxDB does have its merits, it could lead to more users inadvertently installing an outdated version, especially since InfluxDB v1 is currently the only version listed by default in Home Assistant. This can be misleading for beginner users who may not realize they are starting with an obsolete version.

To address these concerns, I propose the following steps:

1. **Release an Updated Version**: We can introduce the InfluxDB v2 Add-on as a new version while providing clear instructions for existing users on how to upgrade.

2. **Documentation on Breaking Changes**: Adding a section in the README to inform users about the breaking changes and highlight the new setup required for InfluxDB v2, mabye in the release notes so its more visible in Home Assistant

3. **Reference the Migration Guide**: As suggested, we can include a link to the official migration guide ([InfluxDB v1 to v2 Migration Guide](https://docs.influxdata.com/influxdb/v2/install/upgrade/v1-to-v2/)) to help users understand the changes and facilitate their transition.

By the way, I do not have a experience with building Add-ons for Home Assistant, so could you clarify what you mean by your first comment?

**Pull request closed without merging**
